### PR TITLE
Create README.md

### PR DESCRIPTION
**Pull request by srl295**

### CODE REVIEW

**Review by Ken-Whistler — COMMENTED** [review]
The the title, how about just "... the Unicode Consortium on GitHub" instead of "...the Unicode Consortium's organization on GitHub". For the purpose I would add "... for character encoding and internationalization of..." rather than omitting character encoding. Fits better with our stated purpose in the bylaws.

**Review by rickmcgowan — COMMENTED** [review]
Tend to agree with Ken's note. Otherwise fine. We can adjust as needed later.

**Comment by srl295** [comment]
@rickmcgowan @Ken-Whistler thanks, I updated the wording, see if it looks better now

**Review by Ken-Whistler — APPROVED** [review]
Looks o.k. now

**Pull request merged**
